# the context/scenario to be used by the dialogue manager
# must have a folder with the same name including all the relevant inforamtion: grammar, parser config file, map templates, and knowledge base if using sqlite
context: EvacuationExample
parser_dir: /Parser
kbase:
  # -------------------
  # sqlite
  type: sqlite
  dbfile: /KBase/kboop.sqlite
  # -------------------
  # -------------------
  # postgresql
  #type: postgresql
  #host: spatiallab.ist.psu.edu
  #port: 5432
  #dbname: evacuation
  #user: kbase
  #password: ist309
  # -------------------
# the directory including at least one executor and one responder
actuator: Actuator
# the executor defines the basic actions that the system can perform as defined in the knowledge base
executor: 
  module: Actuator.EvacExecutor
  class: EvacExecutor
responders: 
  # it is possible to have multiple responders, e.g. different modals, or different experimental strategies
  - module: Actuator.TextResponder
    class: TextResponder
  - module: Actuator.MapResponder
    class: MapResponder
  #- module: MapResponder1
  #  class: MapResponder1
  #- module: MapResponder2
  #  class: MapResponder2
  #- module: MapResponder3
  #  class: MapResponder3